#!/bin/bash
echo "/!\ Leia, falante de português (Em inglês); Léelo, hispanohablante (Em inglês): Portuguese and Spanish languages are not available for organizational reasons. Sorry about it :("
echo
echo "x----- 🛒️ BRAppStore 🛍️ -----x"
echo
echo "=== ❗️ ABOUT ==="
echo 'Hello, welcome to BRAppStore! BRAppStore is an official repository of BashRun created in order to facilitate the running of scripts, like the installation of applications and games for Linux. Feel yourself at home!'
echo 'For requests to add applications or games to the repository, create a new issue with the title starting at "BRAppStore:" + "Name of requested program", and with the "BR at this link: https://github.com/Felipecconde/scripts/issues/new'
echo
echo "=== 📰️ NEWS ==="
echo "Nothing here, sorry :("
echo
echo "=== 🕒️ COMING SOON ===
echo "Name: osu!lazer | Description: osu! installer for Linux | Category: Game | Command: br osulazer"
echo "Name: Genshin Impact | Description: Genshin Impact installer for Linux | Category: Game | Command: br genshinimpact"
echo
echo "=== ⬇️ ACCESS FULL REPOSITORY ==="
echo "To list the full BRAppStore repository, use 'br repoappstore' command. We recommend the usage of 'grep' command to filter/search on the repository."
echo
echo "x--------------------------X"
