#!/bin/bash
echo "=== ATUALIZAR/UPDATE/ACTUALIZAR ===
echo
echo "[PT]: Atualizando BashRun, aguarde..."
echo
echo "[EN]: Updating BashRun, please wait..."
echo
echo "[ES]: Actualizando BashRun, espere..."
echo
sudo apt -y install git > /dev/null 2>&1
rm -rf $HOME/Downloads/br > /dev/null 2>&1
git clone https://github.com/Felipecconde/br $HOME/Downloads/br > /dev/null 2>&1
sudo chmod +x $HOME/Downloads/br/br/br-installer.sh > /dev/null 2>&1
bash $HOME/Downloads/br/br/br-installer.sh > /dev/null 2>&1
rm -rf $HOME/Downloads/br > /dev/null 2>&1
echo "=== CONLUÍDO/DONE/HECHO ===
echo
echo "[PT]: Atualização concluída! Desfrute do BashRun!"
echo
echo "[EN]: Update completed! Enjoy BashRun!"
echo
echo "[ES]: ¡Actualizacion completa! ¡Disfruta de BashRun!"
exit
