#!/bin/bash
VER=$(curl --silent "https://api.github.com/repos/ppy/osu/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")' | tr -d .)
INSTALLVER=$(cat $HOME/.brappstore/osu'!'lazer | tr -d .)
if (( $VER > $INSTALLVER )); then
echo need_update
yes "i" | sudo br osulazer
else
echo already_updated
fi
